# Generated by Django 2.2.10 on 2020-03-03 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total', models.FloatField()),
                ('cantidad_productos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField()),
                ('numero_tarjeta', models.CharField(blank=True, default='', max_length=16)),
                ('cv', models.IntegerField()),
                ('fecha_vencimiento', models.CharField(blank=True, default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=45)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, default='', max_length=45)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='administracion/imagenes')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_recepcionista', models.CharField(blank=True, default='', max_length=45)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=45)),
                ('distrito', models.CharField(blank=True, default='', max_length=45)),
                ('provincia', models.CharField(blank=True, default='', max_length=45)),
                ('departamento', models.CharField(blank=True, default='', max_length=45)),
                ('nombre_comprador', models.CharField(blank=True, default='', max_length=45)),
                ('id_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Cotizacion')),
                ('id_cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.CuentaBancaria')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('id_cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Cotizacion')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Producto')),
            ],
        ),
    ]
