# Generated by Django 2.2.10 on 2020-02-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=True, to='administracion.Producto'),
        ),
    ]
