# Generated by Django 2.2.10 on 2020-02-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_producto_id_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='hola',
        ),
    ]
