# Generated by Django 2.2.10 on 2020-02-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20200217_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='administracion/imagenes'),
        ),
    ]
