# Generated by Django 2.2.10 on 2020-02-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='administracion.Producto'),
        ),
    ]
